routes/web.php
<?php
if (env('APP_ENV') === 'local') {
    URL::forceScheme('https');
}
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Spatie\GoogleCalendar\Event;

//Route::get('/', function () {
//    $event = new \Spatie\GoogleCalendar\Event();
//    $event->name = "test App event";
//    $event->startDateTime = Carbon\Carbon::now();
//    $event->endDateTime = Carbon\Carbon::now()->addHour();
//    $event->addAttendee([
//        'email' => 'azeemulrehman71@gmail.com',
//        'name' => 'John Doe',
//        'comment' => 'Lorum ipsum',
//    ]);
//    $event->save();
//    $e = Event::get();
//    dd($e);
//});

Route::get('/', function () {
    return view('welcome');
})->name('index');
//
//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', 'Realtor\AppointmentController@oauth')->name('oauthCallback');


//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'gCalendarController@oauth']);

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


//Forget Password
Route::get('/user/verify/{token}', 'Auth\LoginController@activation');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

//Landing Page Routes

Route::get('about-us', 'Frontend\AboutUsController@index')->name('aboutus.detail');
Route::get('how-it-works', 'Frontend\AboutUsController@howItWorks')->name('how.its.works.detail');

Route::post('customer/package/subscribe', 'ChargeController@subscribe')->name('package.subscribe');
Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/states', 'Backend\StateController');
        Route::resource('/packages', 'Backend\PackageController');
        Route::resource('/subscriptions', 'Backend\SubscriptionController');

        Route::post('/states/import/file', 'Backend\StateController@importFile')->name('states.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');


        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/terms-and-conditions', 'Backend\TermsAndConditionsController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });

    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');


    //Customer Routes
    Route::prefix('realtor')->name('realtor.')->group(function () {
        Route::get('/dashboard', 'Realtor\MainController@index')->name('dashboard.index');
        //User Profiles
        Route::get('profile', 'Realtor\ProfileController@index')->name('profile.index');
        Route::get('subscribe/package', 'Realtor\MainController@subcribePackage')->name('subscribe.package');
        Route::get('subscribe-history', 'Realtor\MainController@subscribeHistory')->name('subscribe.history.index');

        Route::get('notifications', 'Realtor\MainController@notifications')->name('notifications.index');

        Route::get('edit/profile', 'Realtor\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Realtor\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Realtor\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Realtor\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Realtor\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Realtor\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Realtor\ProfileController@updateMobileNumber')->name('update.user.phone');


        Route::resource('/appointments', 'Realtor\AppointmentController');

        Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'Realtor\AppointmentController@oauth']);
        Route::post('appointment-time-increment', 'Realtor\AppointmentController@timeIncreament');
        Route::post('appointment-checkin', 'Realtor\AppointmentController@checkIn');
        Route::post('appointment-checkout', 'Realtor\AppointmentController@checkOut');
        Route::get('appointment-calender-google', 'Realtor\AppointmentController@googleCalenderAppointment');


        Route::get('cancel/appointment', 'Realtor\AppointmentController@cancelAppointment')->name('cancel.appointment.status');


    });

    Route::get('payment', 'ChargeController@finalPayment')->name('payment');


});

Route::get('code/{code}', 'Realtor\BackgroundCheckController@getCode');
Route::get('realtor/appointment/background/check/{appointment_id}/{user_id}', 'Realtor\BackgroundCheckController@appointmentCheck');
Route::post('realtor/appointment/background/store/{appointment_id}', 'Realtor\BackgroundCheckController@storeBackgroundCheck')->name('realtor.appointments.store.backgroundCheck');


Route::get('privacy-policy', function () {
    $privacyPolicy = \App\Models\PrivacyPolicy::first();
    return view('frontend.pages.privacy-policy', compact('privacyPolicy'));
})->name('privacy.policy');

Route::get('terms-and-conditions', function () {
    $terms = \App\Models\TermsAndCondition::first();
    return view('frontend.pages.terms-and-conditions', compact('terms'));
})->name('terms-and-conditions');


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {

    Route::post('update/addon/checks', 'Backend\AjaxController@updateAddOnChecks')->name('update.addon.checks');
    Route::get('state-cities', 'Backend\AjaxController@stateCities')->name('stateCities');
    Route::get('backgroundCheck', 'Backend\AjaxController@xmlRequestBackgroundCheck')->name('backgroundCheck');

});


Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);


Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');


//Basic Charge
Route::post('/charge', 'ChargeController@charge')->name('charge');
Route::get('/send/sms/user', 'SMSController@sendSms')->name('send.sms.user');

app/Models/Realtor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Realtor extends Model
{
    protected $table = 'realtors';
    protected $guarded = [];
    use SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function appointments()
    {
        return $this->belongsToMany(Appointment::class, 'appointment_schedules', 'appointment_id', 'realtor_id');
    }

    public function packages()
    {
        return $this->hasOne(Package::class, 'subscriptions', 'package_id', 'realtor_id');
    }

    public function packageSubcriptionHistory()
    {
        return $this->belongsToMany(Package::class, 'subscription_histories', 'package_id', 'realtor_id');
    }

}

app/Http/Controllers/Backend/ProfileController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\State;
use App\Models\City;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {

        $user = auth()->user();
        return view('backend.profiles.index', compact('user'));
    }

    public function editProfile()
    {

        $user = auth()->user();

        $cities = City::all();
        $areas = State::all();
        return view('backend.profiles.edit-profile', compact('user', 'cities', 'areas'));
    }

    public function updateProfile(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'city_id' => 'required|integer',
            'area_id' => 'required|integer',
            'category_id' => 'required|integer',
            'age' => 'required',
            'cnic' => 'required',
            'address' => 'required',
            'email' => 'required|string|email|max:255',
        ], [
            'first_name.required' => 'First name  is required.',
            'last_name.required' => 'Last name  is required.',
            'city_id.required' => 'City is required.',
            'area_id.required' => 'Area  is required.',
            'category_id.required' => 'Gender  is required.',
            'age.required' => 'Age  is required.',
            'cnic.required' => 'CNIC  is required.',
            'email.required' => 'Email  is required.',
        ]);

        $user = User::find(auth()->user()->id);

        $user->update([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'city_id' => $request->get('city_id'),
            'area_id' => $request->get('area_id'),
            'category_id' => $request->get('category_id'),
            'age' => $request->get('age'),
            'cnic' => $request->get('cnic'),
            'address' => $request->get('address'),
            'email' => $request->get('email'),
        ]);

        return redirect()->route('admin.profile.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Profile updated successfully.'
            ]);
    }

    public function editProfileImage(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());
        $user = User::where('id', $request->user_id)->first();

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/user_profiles');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = $user->profile_pic;
        }
        $user->update([
            'profile_pic' => $profile_image,
        ]);

        $response['status'] = 'success';
        $response['message'] = 'Profile Image updated successfully.';

        return $response;


    }

    public function changePassword()
    {

        $user = auth()->user();
        return view('backend.profiles.change-password', compact('user'));
    }

    public function changeMobileNumber()
    {

        $user = auth()->user();
        return view('backend.profiles.change-mobile-number', compact('user'));
    }

    public function updateMobileNumber(Request $request)
    {
        $this->validate($request, [
            'phone_number' => 'required',
        ], [
            'phone_number.required' => 'Mobile Number is required.',

        ]);

        $user = User::find(auth()->user()->id);

        $user->update([
            'phone_number' => $request->get('phone_number'),
        ]);

        return redirect()->route('admin.profile.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Mobile Number updated successfully.'
            ]);
    }

    public function updatePassword(Request $request)
    {
        if (!(Hash::check($request->get('current-password'), auth()->user()->password))) {
            // The passwords matches
            return redirect()->back()->with("error", "Your current password does not matches with the password you provided. Please try again.");
        }

        if (strcmp($request->get('current-password'), $request->get('new-password')) == 0) {
            //Current password and new password are same
            return redirect()->back()->with("error", "New Password cannot be same as your current password. Please choose a different password.");
        }

        $validatedData = $request->validate([
            'current-password' => 'required',
            'new-password' => 'required|string|min:6',
        ]);

        if (strcmp($request->get('new-password-confirm'), $request->get('new-password')) == 0) {
            //Change Password
            $user = Auth::user();
            $user->password = bcrypt($request->get('new-password'));
            $user->save();

            return redirect()->route('admin.profile.index')
                ->with([
                    'flash_status' => 'success',
                    'flash_message' => 'Password Changed successfully.'
                ]);

        } else {
            return redirect()->back()->with("error", "New Password must be same as your confirm password.");
        }


    }
}

app/Http/Controllers/Backend/RealtorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Realtor;

use Illuminate\Http\Request;

class RealtorController extends Controller
{
    public function index()
    {
        $staffs = Realtor::all();
        return view('backend.assign_driver.index', compact('staffs'));
    }
}

resources/views/realtor/profiles/change-mobile-number.blade.php
@extends('realtor.main')
@section('title','Profile')
@push('css')
    <style>
        .serviceInner {
            height: 280px;
        }

        .bannerFields {
            margin-top: 15px;
        }
    </style>
@endpush
@section('content')
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="">
                <div class="">
                    <div class="m-portlet">
                        <div class="container">
                            <div class="m-portlet__body">
                                <div class="serviceBoxMain">
                                    <div class="serverInnerDetails">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-6 col-xs-12 bannerFields">
                                                <form action="{{ route('realtor.update.user.phone') }}"
                                                      method="post" enctype="multipart/form-data">
                                                    @csrf
                                                    <div class="row">
                                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                                            <div class="form-group">
                                                                <label for="phone_number">Enter New Mobile
                                                                    Number</label>
                                                                <input type="tel" class="form-control"
                                                                       name="phone_number" id="phone_number"
                                                                       autocomplete="phone_number" autofocus placeholder="03001234567"
                                                                       pattern="[03]{2}[0-9]{9}"
                                                                       maxlength="11"
                                                                       onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')"
                                                                       title="Phone number with 03 and remaing 9 digit with 0-9"
                                                                       value="{{ $user->phone_number }}">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-12 col-sm-12 col-xs-12 text-right">
                                                            <a href="{{ route('realtor.profile.index') }}"
                                                               class="btn buttonMain hvr-bounce-to-right">
                                                                Cancel
                                                            </a>
                                                            <button type="submit"
                                                                    class="btn buttonMain hvr-bounce-to-right">Save
                                                                Changes
                                                            </button>
                                                        </div>
                                                    </div>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>

        $('#phone_number').focusout(function () {
            if (/^(03)\d{9}$/.test($(this).val())) {
                // value is ok, use it
            }else {

            }
        });
    </script>
@endpush

resources/views/realtor/profiles/index.blade.php
@extends('realtor.main')
@section('title','Profile')
@push('css')
    <style>
        .profile-image {
            width: 85% !important;
            /*height: 120px;*/
            object-fit: cover;
        }
    </style>
@endpush
@section('content')
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="">
                <div class="">
                    <div class="m-portlet">
                        <div class="container">
                            <div class="m-portlet__body">
                                <div class="serviceBoxMain">
                                    <div class="serverInnerDetails">
                                        <div class="row ">
                                            <div class="col-md-8 col-sm-8 col-xs-12 bannerFields">                                              
                                                <div class="profileSettings">
                                                    <h4>Account Profile</h4>
                                                    <div class="row">
                                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                                            <img class="profile-image"
                                                                     src="{{asset("/uploads/user_profiles/".$user->profile_pic)}}"
                                                                     alt="{{$user->profile_pic}}">
                                                        </div>
                                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                                            <form method="post" enctype="multipart/form-data" id="submit-image"
                                                            action="javascript:void(0)">
                                                            <p>
                                                              @csrf
                                                              <input type="hidden" name="user_id" id="user_id"
                                                                     value="{{ $user->id}}">
      
                                                              <label for="image">
                                                                  <img src="{{ asset('frontend/images/upload.png') }}"
                                                                       style="width: 40px;cursor: pointer;"/>
                                                              </label>
      
                                                              <input type="file" name="image" id="image" style="display: none"
                                                                     onchange="readURL(this);"
                                                                     accept=".png, .jpg, .jpeg"/>
      
                                                                     Change Picture </p>
                                                      </form>
                                                      <p><a href="{{ route('realtor.profile.edit') }}" 
                                                        class=""><i class="fa fa-pencil-alt"></i> &nbsp; Edit Profile</a> </p>
                                                        <table width="100%">
                                                            <tr>
                                                                <td>Name: </td>
                                                                <td>  @if(!is_null($user->membershipDiscount))
                                                                    <span
                                                                        style="color: red">{{ ucfirst($user->membershipDiscount->name) }}</span>
    
                                                                @endif {{ $user->fullName() }} </td>
                                                            </tr>
                                                            <tr>
                                                                <td>Email</td>
                                                                <td>{{ $user->email ?? '--' }}</td>
                                                            </tr>
                                                            <tr>
                                                                <td>Phone Number</td>
                                                                <td>{{ $user->phone_number ?? '--' }}</td>
                                                            </tr>
                                                        </table>
                                                            
                                                          

                                                            <span></span>
                                                            <a href="{{ route('realtor.update.password') }}"
                                                            class="btn buttonMain hvr-bounce-to-right">Reset
                                                             Password</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <table cellpadding="0" cellspacing="0" width="100%">
                                                    <tbody>
                                                    <tr>
                                                        <td>
                                                        </td>
                                                        <td width="30%">
                                                          
                                                        </td>
                                                        <td></td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                                <br>
                                                
                                                <table cellpadding="0" cellspacing="0" width="100%">
                                                    <tbody>

                                                    <tr>

                                                    </tr>

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        function readURL(input, id) {

            if (input.files && input.files[0]) {


                var formData = new FormData($('#submit-image')[0]);
                $.ajax({
                    type: "POST",
                    url: "{{ route('realtor.profile.edit.image') }}",
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        toastr[response.status](response.message);
                        window.location.reload();
                    },
                    error: function () {
                        toastr['error']("Something Went Wrong.");
                    }
                });

                // reader.readAsDataURL(input.files[0]);
                // }
            }
        }
    </script>
@endpush