routes/web.php
<?php
if (env('APP_ENV') === 'local') {
    URL::forceScheme('https');
}
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Spatie\GoogleCalendar\Event;

//Route::get('/', function () {
//    $event = new \Spatie\GoogleCalendar\Event();
//    $event->name = "test App event";
//    $event->startDateTime = Carbon\Carbon::now();
//    $event->endDateTime = Carbon\Carbon::now()->addHour();
//    $event->addAttendee([
//        'email' => 'azeemulrehman71@gmail.com',
//        'name' => 'John Doe',
//        'comment' => 'Lorum ipsum',
//    ]);
//    $event->save();
//    $e = Event::get();
//    dd($e);
//});

Route::get('/', function () {
    return view('welcome');
})->name('index');
//
//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', 'Realtor\AppointmentController@oauth')->name('oauthCallback');


//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'gCalendarController@oauth']);

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


//Forget Password
Route::get('/user/verify/{token}', 'Auth\LoginController@activation');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

//Landing Page Routes

Route::get('about-us', 'Frontend\AboutUsController@index')->name('aboutus.detail');
Route::get('how-it-works', 'Frontend\AboutUsController@howItWorks')->name('how.its.works.detail');

Route::post('customer/package/subscribe', 'ChargeController@subscribe')->name('package.subscribe');
Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/states', 'Backend\StateController');
        Route::resource('/packages', 'Backend\PackageController');
        Route::resource('/subscriptions', 'Backend\SubscriptionController');

        Route::post('/states/import/file', 'Backend\StateController@importFile')->name('states.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');


        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/terms-and-conditions', 'Backend\TermsAndConditionsController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });

    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');


    //Customer Routes
    Route::prefix('realtor')->name('realtor.')->group(function () {
        Route::get('/dashboard', 'Realtor\MainController@index')->name('dashboard.index');
        //User Profiles
        Route::get('profile', 'Realtor\ProfileController@index')->name('profile.index');
        Route::get('subscribe/package', 'Realtor\MainController@subcribePackage')->name('subscribe.package');
        Route::get('subscribe-history', 'Realtor\MainController@subscribeHistory')->name('subscribe.history.index');

        Route::get('notifications', 'Realtor\MainController@notifications')->name('notifications.index');

        Route::get('edit/profile', 'Realtor\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Realtor\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Realtor\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Realtor\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Realtor\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Realtor\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Realtor\ProfileController@updateMobileNumber')->name('update.user.phone');


        Route::resource('/appointments', 'Realtor\AppointmentController');

        Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'Realtor\AppointmentController@oauth']);
        Route::post('appointment-time-increment', 'Realtor\AppointmentController@timeIncreament');
        Route::post('appointment-checkin', 'Realtor\AppointmentController@checkIn');
        Route::post('appointment-checkout', 'Realtor\AppointmentController@checkOut');
        Route::get('appointment-calender-google', 'Realtor\AppointmentController@googleCalenderAppointment');


        Route::get('cancel/appointment', 'Realtor\AppointmentController@cancelAppointment')->name('cancel.appointment.status');


    });

    Route::get('payment', 'ChargeController@finalPayment')->name('payment');


});

Route::get('code/{code}', 'Realtor\BackgroundCheckController@getCode');
Route::get('realtor/appointment/background/check/{appointment_id}/{user_id}', 'Realtor\BackgroundCheckController@appointmentCheck');
Route::post('realtor/appointment/background/store/{appointment_id}', 'Realtor\BackgroundCheckController@storeBackgroundCheck')->name('realtor.appointments.store.backgroundCheck');


Route::get('privacy-policy', function () {
    $privacyPolicy = \App\Models\PrivacyPolicy::first();
    return view('frontend.pages.privacy-policy', compact('privacyPolicy'));
})->name('privacy.policy');

Route::get('terms-and-conditions', function () {
    $terms = \App\Models\TermsAndCondition::first();
    return view('frontend.pages.terms-and-conditions', compact('terms'));
})->name('terms-and-conditions');


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {

    Route::post('update/addon/checks', 'Backend\AjaxController@updateAddOnChecks')->name('update.addon.checks');
    Route::get('state-cities', 'Backend\AjaxController@stateCities')->name('stateCities');
    Route::get('backgroundCheck', 'Backend\AjaxController@xmlRequestBackgroundCheck')->name('backgroundCheck');

});


Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);


Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');


//Basic Charge
Route::post('/charge', 'ChargeController@charge')->name('charge');
Route::get('/send/sms/user', 'SMSController@sendSms')->name('send.sms.user');

app/Models/Appointment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    protected $table = "appointments";
    protected $guarded = [];


    public function realtors()
    {
        return $this->belongsToMany(Realtor::class, 'appointment_schedules', 'realtor_id', 'appointment_id');
    }

    public function state()
    {
        return $this->belongsTo(State::class, 'property_state', 'id');
    }

    public function city()
    {
        return  $this->belongsTo(City::class, 'property_city', 'id');
    }


}

app/Models/Realtor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Realtor extends Model
{
    protected $table = 'realtors';
    protected $guarded = [];
    use SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function appointments()
    {
        return $this->belongsToMany(Appointment::class, 'appointment_schedules', 'appointment_id', 'realtor_id');
    }

    public function packages()
    {
        return $this->hasOne(Package::class, 'subscriptions', 'package_id', 'realtor_id');
    }

    public function packageSubcriptionHistory()
    {
        return $this->belongsToMany(Package::class, 'subscription_histories', 'package_id', 'realtor_id');
    }

}

app/Http/Controllers/Backend/AppointmentController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AppointmentController extends Controller
{
    //
}

app/Http/Controllers/Backend/RealtorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Realtor;

use Illuminate\Http\Request;

class RealtorController extends Controller
{
    public function index()
    {
        $staffs = Realtor::all();
        return view('backend.assign_driver.index', compact('staffs'));
    }
}

app/Http/Controllers/Realtor/BackgroundCheckController.php
<?php

namespace App\Http\Controllers\Realtor;

use App\Http\Controllers\Controller;
use App\Models\Appointment;
use App\Models\AppointmentSchedule;
use App\Models\BackgroundCheck;
use App\Models\ShortLink;
use App\Models\State;
use App\Models\User;
use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class BackgroundCheckController extends Controller
{

    use GeneralHelperTrait;

    public function getCode($code)
    {
        $url = ShortLink::where('code', $code)->first()->link;
        return redirect()->to($url);
    }

    public function appointmentCheck($appointment_schedule_id, $user_id)
    {

        $user = User::where('id', $user_id)->first();
        Auth::login($user);
        $getAppoitment = AppointmentSchedule::with(['appointment', 'emergencyContacts', 'backgroundCheck'])->where('id', $appointment_schedule_id)->first();

        $states = State::orderBy('name', 'asc')->get();
        $cities = DB::table('cities')->where('id', (int)$getAppoitment->appointment->property_city)->get();

        return view('realtor.appointments.appointment')->with([
            'getAppointment' => $getAppoitment,
            'user' => $user,
            'states' => $states,
            'cities' => $cities,

        ]);
    }

    public function storeBackgroundCheck(Request $request, $appointmen_id)
    {
        $appointmentSchedule = AppointmentSchedule::where('id', $request->appointment_schedule_id)->first();
        $appointment = Appointment::where('id', $appointmen_id)->first();

        if ($request->bg_status == 'rejected') {
            $appointment->bg_status = 'rejected';
        }
        if ($request->bg_status == 'accepted') {
            $appointment->bg_status = 'accepted';
        }
        $appointment->cl_first_name = $request->cl_first_name;
        $appointment->cl_last_name = $request->cl_last_name;
        $appointment->cl_dob = $request->cl_dob;
        $appointment->cl_doc_id_number = $request->cl_doc_id_number;
        $appointment->cl_doc_id_state = $request->cl_doc_id_state;
        $appointment->cl_email = $request->cl_email;
        $appointment->cl_mobile_number = $request->cl_mobile_number;
        $appointment->property_address_one = $request->property_address_one;
        $appointment->property_address_two = $request->property_address_two;
        $appointment->property_city = $request->property_city;
        $appointment->property_state = $request->property_state;
        $appointment->property_zip_code = $request->property_zip_code;
        if ($request->has('upload_doc')) {
            $image = $request->file('upload_doc');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/appointmentImage');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = 'default.png';
        }
        $appointment->image = $profile_image;
        $appointment->save();
        if ($appointmentSchedule->background_check == "1") {

            if (!is_null($request->final_firstname)) {
                $checkRecordBg = BackgroundCheck::where('ssn', $request->final_ssn)->first();
                if (!is_null($checkRecordBg)) {
                    $backgroundCheck = $checkRecordBg;
                } else {
                    $backgroundCheck = new BackgroundCheck();
                }
                $backgroundCheck->appointment_schedule_id = $appointmentSchedule->id;
                $backgroundCheck->first_name = $request->final_firstname;
                $backgroundCheck->last_name = $request->final_lastname;
                $backgroundCheck->ssn = $request->final_ssn;
                $backgroundCheck->dob = $request->final_dob;
                $backgroundCheck->city = $request->final_city;
                $backgroundCheck->state = $request->final_state;
                $backgroundCheck->save();
            }
        }


        return redirect()->route('index')->with(['flash_status' => "success", 'flash_message' => "Appointment Updated Successfully!"]);

    }
}

resources/views/realtor/appointments/index.blade.php
@extends('realtor.main')
@section('title','Appointments')
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Appointments
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('realtor.appointments.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Appointment</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="m-portlet__body">
                <input type="hidden">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th> Sr NO.</th>
                        <th> Full Name</th>
                        <th> Address</th>
                        <th> Appointment Date</th>
                        <th> Appointment Time</th>
                        <th> Status</th>
                        <th> BG Status</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($appointments))
                        @foreach($appointments as $appointment)

                            @php
                                $start_time     =  date('h:i A', strtotime($appointment->start_time));
                                $end_time       =  date('h:i A', strtotime($appointment->end_time));
                                $start_date     =  date('l j F, Y', strtotime($appointment->start_date));

                            @endphp
                            <tr style="background:@if($appointment->appointment->bg_status == 'not-applied') yellow;  @elseif($appointment->appointment->bg_status == 'accepted') lightgreen; @elseif($appointment->appointment->bg_status == 'rejected') red; @endif color: @if($appointment->appointment->bg_status == 'rejected') #fff @else #000; @endif">

                                <td>{{$loop->iteration}}</td>
                                <td>{{ucfirst($appointment->appointment->cl_first_name)}} {{ucfirst($appointment->appointment->cl_last_name)}}</td>
                                <td>{{$appointment->appointment->property_address_one}} {{$appointment->appointment->property_address_two}}
                                    , {{ (!is_null($appointment->appointment->city)) ? $appointment->appointment->city->name :' ' }}
                                    , {{(!is_null($appointment->appointment->state)) ? $appointment->appointment->state->name : '' }}</td>
                                <td>{{$start_date}}</td>
                                <td>{{$start_time}} - {{$end_time}}</td>
                                <td>{{ucfirst($appointment->status)}}</td>
                                <td>
                                    @if($appointment->appointment->bg_status == 'not-applied')
                                        Background Check not performed
                                    @elseif($appointment->appointment->bg_status == 'accepted')
                                        Background Check is passed
                                    @elseif($appointment->appointment->bg_status == 'rejected')
                                        Background Check is Failed
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('realtor.appointments.edit', $appointment->id) }}">
                                        <button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Edit">Edit<i
                                                class="fa fa-pencil"></i></button>
                                    </a>
                                    @if($appointment->status =='upcoming')
                                        <a href="javascript:void(0)">
                                            <button class="btn btn-xs btn-primary cancelAppointment" style="margin-top: 3px;"
                                                    id="cancelAppointment" data-id="{{$appointment->id}}"
                                                    data-toggle="tooltip" title="Cancel">Cancel<i
                                                    class="fa fa-cancel"></i></button>
                                        </a>
                                    @endif
                                </td>



                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "ordering": false,
            "order": [[0, "desc"]],
            "columnDefs": [
                {orderable: false, targets: [5]}
            ],
        });
        $(document).on('click', '.cancelAppointment', function () {

            var appointment_schedule_id = $(this).data('id');
            var request = {"appointment_schedule_id": appointment_schedule_id};
            if (appointment_schedule_id !== '') {
                $.ajax({
                    type: "GET",
                    url: "{{ route('realtor.cancel.appointment.status') }}",
                    data: request,
                    dataType: "json",
                    cache: true,
                    success: function (response) {
                        if (response.status === "success") {
                            toastr[response.status](response.message);
                            window.location.href = '{{ route('realtor.appointments.index') }}'
                        }
                    },
                    error: function () {
                        toastr['error']('Something went wrong.');
                    }
                });
            } else {
                toastr['error']('Appointment Schedule not found.');

            }

        });


    </script>
@endpush