routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/

//use Spatie\GoogleCalendar\Event;

//Route::get('/', function () {
//    $event = new \Spatie\GoogleCalendar\Event();
//    $event->name = "test App event";
//    $event->startDateTime = Carbon\Carbon::now();
//    $event->endDateTime = Carbon\Carbon::now()->addHour();
//    $event->addAttendee([
//        'email' => 'azeemulrehman71@gmail.com',
//        'name' => 'John Doe',
//        'comment' => 'Lorum ipsum',
//    ]);
//    $event->save();
//    $e = Event::get();
//    dd($e);
//});

Route::get('/', function () {
    return view('welcome');
})->name('index');
//
//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', 'Realtor\AppointmentController@oauth')->name('oauthCallback');


//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'gCalendarController@oauth']);

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


//Forget Password
Route::get('/user/verify/{token}', 'Auth\LoginController@activation');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

//Landing Page Routes

Route::get('about-us', 'Frontend\AboutUsController@index')->name('aboutus.detail');
Route::get('how-it-works', 'Frontend\AboutUsController@howItWorks')->name('how.its.works.detail');

Route::post('customer/package/subscribe', 'ChargeController@subscribe')->name('package.subscribe');
Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/states', 'Backend\StateController');
        Route::resource('/packages', 'Backend\PackageController');
        Route::resource('/subscriptions', 'Backend\SubscriptionController');

        Route::post('/states/import/file', 'Backend\StateController@importFile')->name('states.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');


        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/terms-and-conditions', 'Backend\TermsAndConditionsController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });

    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');


    //Customer Routes
    Route::prefix('realtor')->name('realtor.')->group(function () {
        Route::get('/dashboard', 'Realtor\MainController@index')->name('dashboard.index');
        //User Profiles
        Route::get('profile', 'Realtor\ProfileController@index')->name('profile.index');
        Route::get('subscribe/package', 'Realtor\MainController@subcribePackage')->name('subscribe.package');
        Route::get('subscribe-history', 'Realtor\MainController@subscribeHistory')->name('subscribe.history.index');

        Route::get('notifications', 'Realtor\MainController@notifications')->name('notifications.index');

        Route::get('edit/profile', 'Realtor\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Realtor\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Realtor\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Realtor\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Realtor\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Realtor\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Realtor\ProfileController@updateMobileNumber')->name('update.user.phone');


        Route::resource('/appointments', 'Realtor\AppointmentController');

        Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'Realtor\AppointmentController@oauth']);
        Route::post('appointment-time-increment', 'Realtor\AppointmentController@timeIncreament');
        Route::post('appointment-checkin', 'Realtor\AppointmentController@checkIn');
        Route::post('appointment-checkout', 'Realtor\AppointmentController@checkOut');
        Route::get('appointment-calender-google', 'Realtor\AppointmentController@googleCalenderAppointment');


        Route::get('cancel/appointment', 'Realtor\AppointmentController@cancelAppointment')->name('cancel.appointment.status');


    });

    Route::get('payment', 'ChargeController@finalPayment')->name('payment');


});

Route::get('code/{code}', 'Realtor\BackgroundCheckController@getCode');
Route::get('realtor/appointment/background/check/{appointment_id}/{user_id}', 'Realtor\BackgroundCheckController@appointmentCheck');
Route::post('realtor/appointment/background/store/{appointment_id}', 'Realtor\BackgroundCheckController@storeBackgroundCheck')->name('realtor.appointments.store.backgroundCheck');


Route::get('privacy-policy', function () {
    $privacyPolicy = \App\Models\PrivacyPolicy::first();
    return view('frontend.pages.privacy-policy', compact('privacyPolicy'));
})->name('privacy.policy');

Route::get('terms-and-conditions', function () {
    $terms = \App\Models\TermsAndCondition::first();
    return view('frontend.pages.terms-and-conditions', compact('terms'));
})->name('terms-and-conditions');


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {

    Route::post('update/addon/checks', 'Backend\AjaxController@updateAddOnChecks')->name('update.addon.checks');
    Route::get('state-cities', 'Backend\AjaxController@stateCities')->name('stateCities');
    Route::get('backgroundCheck', 'Backend\AjaxController@xmlRequestBackgroundCheck')->name('backgroundCheck');

});


Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);


Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');


//Basic Charge
Route::post('/charge', 'ChargeController@charge')->name('charge');
Route::get('/send/sms/user', 'SMSController@sendSms')->name('send.sms.user');


Route::post('/customer/charge', 'ChargeController@chargeWithMerchantAndCustomer')->name('customer.charge');

Route::group(['prefix' => 'merchant'], function () {

    //Charge with merchant
    Route::get('/{merchant}/charge', 'ChargeController@chargeWithMerchant');

    //Charge with merchant and customer

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;
use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('backend.aboutus.create', compact('aboutus'));
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'summary' => 'required',
            'description' => 'required',
        ], [
            'summary.required' => 'Summary is required.',
            'description.required' => 'Description is required.'
        ]);
        $aboutus = Aboutus::findOrFail(1);

        $aboutus->update([
            'summary' => $request->summary,
            'description' => $request->description
        ]);
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'About us description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\City;
use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use App\Models\Subscription;


class AjaxController extends Controller
{
    use GeneralHelperTrait;

    public function example(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
        ], [

        ]);

        if (!$validator->fails()) {


            $response['status'] = 'success';
            $response['data'] = [

            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }

    public function updateAddOnChecks(Request $request)
    {
        $response = array('status' => '', 'message' => "");

        $getSubscription = Subscription::with('package')->where('id', $request->Id)->first();
        if (isset($getSubscription)) {
            $total_add_on = $request->newAddOn;
            $total_price = ($total_add_on * $getSubscription->package->addon_price) + $getSubscription->package->price;

            $getSubscription->addon_checks = $total_add_on;
            $getSubscription->price = $total_price;
            $getSubscription->save();
        }

        $response['status'] = 'success';
        $response['message'] = 'Addon Checks Updated sucessfully.';
        return $response;
    }

    public function stateCities(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'state_id' => 'required|exists:states,id'
        ], [
            'state_id.required' => "State is Required.",
            'state_id.exists' => "Invalid State Selected."
        ]);

        if (!$validator->fails()) {
            $cities = City::where('state_id', $request->state_id)->orderBy('name', 'asc')->get();

            $response['status'] = 'success';
            $response['data'] = [
                'cities' => $cities,
            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }

    public function xmlRequestBackgroundCheck(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());
        $user = Auth::user();
        $subscriptionRemaining = Subscription::orderBy('id', 'DESC')->where('realtor_id', $user->realtor->id)->first();

        if (!is_null($subscriptionRemaining) && $subscriptionRemaining->remaining_checks > 0) {

            $subscriptionRemaining->remaining_checks = $subscriptionRemaining->remaining_checks - 1;
            $subscriptionRemaining->save();


            $response['status'] = 'success';
            $response['data'] = [
                'backgroundCheckResponse' => $this->xmlRequest($request->first_name, $request->first_name, date('m/d/Y', strtotime($request->dob))),
            ];
        } else {

            $response['status'] = 'error';
            $response['message'] = 'No Background Check Available';
            $response['data'] = [
                'backgroundCheckResponse' => [],
            ];
        }


        return $response;


    }


}

app/Http/Controllers/Backend/AppointmentController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AppointmentController extends Controller
{
    //
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\City;
use App\Models\Order;
use App\Models\State;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CityController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index(Request $request)
    {
        ini_set('max_execution_time', 300);


        if (!is_null($request->state_id)) {

            $cities = DB::table('cities')->where('state_id', (int)$request->state_id)->orderBy('name', 'ASC')->get();

        } else {
            $cities = [];
        }
        $states = State::orderBy('name', 'ASC')->get();

//        $cities =DB::table('cities')->select('id','name','state_id')->orderBy('name', 'ASC')->limit(100000)->get();

        return view('backend.cities.index', compact('cities', 'states'));
    }

    public function create()
    {
        $states = State::orderBy('name', 'ASC')->get();
        return view('backend.cities.create', compact('states'));

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'state_id' => 'required',
        ]);
        City::create($request->all());
        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City created successfully.'
            ]);

    }

    public function edit($id)
    {
        $city = City::find($id);
        $states = State::orderBy('name', 'ASC')->get();
        return view('backend.cities.edit', compact('city', 'states'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'state_id' => 'required',
        ]);
        City::find($id)->update($request->all());
        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $city = City::findOrFail($id);
        $city->delete();

        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users_count = User::all()->count();
        $staff_users = User::where('user_type', 'realtor')->get()->toArray();

        return view('backend.dashboard.index', compact('users_count', 'staff_users'));
    }
}

resources/views/backend/subscriptions/create.blade.php
@extends('layouts.master')
@section('title','Cities')
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Add {{ __('City') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.cities.store') }}"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">

                                    <div class="form-group row">


                                        <div class="col-md-6">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('City Name') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{{ old('name') }}"
                                                   autocomplete="name" autofocus>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="slug"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Slug') }} <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="slug" type="text"
                                                   class="form-control @error('slug') is-invalid @enderror"
                                                   name="slug" value="{{ old('slug') }}"
                                                   autocomplete="slug" autofocus>

                                            @error('slug')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.cities.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $('#name').focusout(function () {

            var name = $(this).val();
            name = name.replace(/\s+/g, '-').toLowerCase();

            $('#slug').val(name);
        })
    </script>
@endpush

resources/views/backend/subscriptions/edit.blade.php
@extends('layouts.master')
@section('title','Subscriptions')
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Edit {{ __('Subscription') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.subscriptions.update', $subscription->id) }}"
                              enctype="multipart/form-data" role="form">
                            @method('patch')
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">


                                    <div class="form-group row">


                                        <div class="col-md-6">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Realtor Name') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{!! $subscription->realtor->user->fullName() !!}"
                                                   autocomplete="name" autofocus readonly>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Package Name') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{!! $subscription->package->name !!}"
                                                   autocomplete="name" autofocus readonly>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="price"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Price') }} <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="price" type="number"
                                                   class="form-control @error('price') is-invalid @enderror"
                                                   name="price" value="{!! $subscription->price !!}"
                                                   autocomplete="price" autofocus>

                                            @error('price')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="background_checks"
                                                   class="col-md-6 col-form-label text-md-left">{{ __('Background Checks') }} <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="background_checks" type="number"
                                                   class="form-control @error('background_checks') is-invalid @enderror"
                                                   name="background_checks" value="{!! $subscription->background_checks !!}"
                                                   autocomplete="background_checks" autofocus>

                                            @error('background_checks')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.subscriptions.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script>

    </script>
@endpush

resources/views/backend/subscriptions/index.blade.php
@extends('layouts.master')
@section('title','Subscriptions')
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Subscriptions
                        </h3>
                    </div>
                </div>

            </div>

            <div class="m-portlet__body">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th> Sr NO.</th>
                        <th> Realtor Name</th>
                        <th> Package Name</th>
                        <th> Price</th>
                        <th> Background Checks</th>
                        <th> Payment Status</th>
                        <th> Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($subscriptions))
                        @foreach($subscriptions as $subscription)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$subscription->realtor->user->fullName()}}</td>
                                <td>{{$subscription->package->name}}</td>
                                <td>{{$subscription->price}}</td>
                                <td>{{$subscription->background_checks}}</td>
                                <td>{{ucwords($subscription->status)}}</td>
                                <td nowrap>
                                    <a href="{{route('admin.subscriptions.edit',$subscription->id)}}" class="btn btn-sm btn-info pull-left ">Edit</a>

                                </td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $("#m_table_1").dataTable({
            "columnDefs": [
                { orderable: false, targets: [2] }
            ],
        });
    </script>
@endpush