routes/web.php
<?php
if (env('APP_ENV') === 'local') {
    URL::forceScheme('https');
}
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Spatie\GoogleCalendar\Event;

//Route::get('/', function () {
//    $event = new \Spatie\GoogleCalendar\Event();
//    $event->name = "test App event";
//    $event->startDateTime = Carbon\Carbon::now();
//    $event->endDateTime = Carbon\Carbon::now()->addHour();
//    $event->addAttendee([
//        'email' => 'azeemulrehman71@gmail.com',
//        'name' => 'John Doe',
//        'comment' => 'Lorum ipsum',
//    ]);
//    $event->save();
//    $e = Event::get();
//    dd($e);
//});

Route::get('/', function () {
    return view('welcome');
})->name('index');
//
//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', 'Realtor\AppointmentController@oauth')->name('oauthCallback');


//Route::resource('cal', 'gCalendarController');
//Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'gCalendarController@oauth']);

Auth::routes(['verify' => true]);
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


//Forget Password
Route::get('/user/verify/{token}', 'Auth\LoginController@activation');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');

//Landing Page Routes

Route::get('about-us', 'Frontend\AboutUsController@index')->name('aboutus.detail');
Route::get('how-it-works', 'Frontend\AboutUsController@howItWorks')->name('how.its.works.detail');

Route::post('customer/package/subscribe', 'ChargeController@subscribe')->name('package.subscribe');
Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/states', 'Backend\StateController');
        Route::resource('/packages', 'Backend\PackageController');
        Route::resource('/subscriptions', 'Backend\SubscriptionController');

        Route::post('/states/import/file', 'Backend\StateController@importFile')->name('states.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');


        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/terms-and-conditions', 'Backend\TermsAndConditionsController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });

    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');


    //Customer Routes
    Route::prefix('realtor')->name('realtor.')->group(function () {
        Route::get('/dashboard', 'Realtor\MainController@index')->name('dashboard.index');
        //User Profiles
        Route::get('profile', 'Realtor\ProfileController@index')->name('profile.index');
        Route::get('subscribe/package', 'Realtor\MainController@subcribePackage')->name('subscribe.package');
        Route::get('subscribe-history', 'Realtor\MainController@subscribeHistory')->name('subscribe.history.index');

        Route::get('notifications', 'Realtor\MainController@notifications')->name('notifications.index');

        Route::get('edit/profile', 'Realtor\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Realtor\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Realtor\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Realtor\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Realtor\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Realtor\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Realtor\ProfileController@updateMobileNumber')->name('update.user.phone');


        Route::resource('/appointments', 'Realtor\AppointmentController');

        Route::get('oauth', ['as' => 'oauthCallback', 'uses' => 'Realtor\AppointmentController@oauth']);
        Route::post('appointment-time-increment', 'Realtor\AppointmentController@timeIncreament');
        Route::post('appointment-checkin', 'Realtor\AppointmentController@checkIn');
        Route::post('appointment-checkout', 'Realtor\AppointmentController@checkOut');
        Route::get('appointment-calender-google', 'Realtor\AppointmentController@googleCalenderAppointment');


        Route::get('cancel/appointment', 'Realtor\AppointmentController@cancelAppointment')->name('cancel.appointment.status');


    });

    Route::get('payment', 'ChargeController@finalPayment')->name('payment');


});

Route::get('code/{code}', 'Realtor\BackgroundCheckController@getCode');
Route::get('realtor/appointment/background/check/{appointment_id}/{user_id}', 'Realtor\BackgroundCheckController@appointmentCheck');
Route::post('realtor/appointment/background/store/{appointment_id}', 'Realtor\BackgroundCheckController@storeBackgroundCheck')->name('realtor.appointments.store.backgroundCheck');


Route::get('privacy-policy', function () {
    $privacyPolicy = \App\Models\PrivacyPolicy::first();
    return view('frontend.pages.privacy-policy', compact('privacyPolicy'));
})->name('privacy.policy');

Route::get('terms-and-conditions', function () {
    $terms = \App\Models\TermsAndCondition::first();
    return view('frontend.pages.terms-and-conditions', compact('terms'));
})->name('terms-and-conditions');


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {

    Route::post('update/addon/checks', 'Backend\AjaxController@updateAddOnChecks')->name('update.addon.checks');
    Route::get('state-cities', 'Backend\AjaxController@stateCities')->name('stateCities');
    Route::get('backgroundCheck', 'Backend\AjaxController@xmlRequestBackgroundCheck')->name('backgroundCheck');

});


Route::resource('/contacts', 'Backend\ContactUsController', [
    'only' => ['create', 'store']
]);


Route::get('/contacts', 'Backend\ContactUsController@create')->name('contacts.create');
Route::post('/contacts/store', 'Backend\ContactUsController@store')->name('contacts.store');


//Basic Charge
Route::post('/charge', 'ChargeController@charge')->name('charge');
Route::get('/send/sms/user', 'SMSController@sendSms')->name('send.sms.user');

app/Models/Realtor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Realtor extends Model
{
    protected $table = 'realtors';
    protected $guarded = [];
    use SoftDeletes;

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function appointments()
    {
        return $this->belongsToMany(Appointment::class, 'appointment_schedules', 'appointment_id', 'realtor_id');
    }

    public function packages()
    {
        return $this->hasOne(Package::class, 'subscriptions', 'package_id', 'realtor_id');
    }

    public function packageSubcriptionHistory()
    {
        return $this->belongsToMany(Package::class, 'subscription_histories', 'package_id', 'realtor_id');
    }

}

app/Http/Controllers/Backend/RealtorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Realtor;

use Illuminate\Http\Request;

class RealtorController extends Controller
{
    public function index()
    {
        $staffs = Realtor::all();
        return view('backend.assign_driver.index', compact('staffs'));
    }
}

app/Http/Controllers/Realtor/BackgroundCheckController.php
<?php

namespace App\Http\Controllers\Realtor;

use App\Http\Controllers\Controller;
use App\Models\Appointment;
use App\Models\AppointmentSchedule;
use App\Models\BackgroundCheck;
use App\Models\ShortLink;
use App\Models\State;
use App\Models\User;
use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class BackgroundCheckController extends Controller
{

    use GeneralHelperTrait;

    public function getCode($code)
    {
        $url = ShortLink::where('code', $code)->first()->link;
        return redirect()->to($url);
    }

    public function appointmentCheck($appointment_schedule_id, $user_id)
    {

        $user = User::where('id', $user_id)->first();
        Auth::login($user);
        $getAppoitment = AppointmentSchedule::with(['appointment', 'emergencyContacts', 'backgroundCheck'])->where('id', $appointment_schedule_id)->first();

        $states = State::orderBy('name', 'asc')->get();
        $cities = DB::table('cities')->where('id', (int)$getAppoitment->appointment->property_city)->get();

        return view('realtor.appointments.appointment')->with([
            'getAppointment' => $getAppoitment,
            'user' => $user,
            'states' => $states,
            'cities' => $cities,

        ]);
    }

    public function storeBackgroundCheck(Request $request, $appointmen_id)
    {
        $appointmentSchedule = AppointmentSchedule::where('id', $request->appointment_schedule_id)->first();
        $appointment = Appointment::where('id', $appointmen_id)->first();

        if ($request->bg_status == 'rejected') {
            $appointment->bg_status = 'rejected';
        }
        if ($request->bg_status == 'accepted') {
            $appointment->bg_status = 'accepted';
        }
        $appointment->cl_first_name = $request->cl_first_name;
        $appointment->cl_last_name = $request->cl_last_name;
        $appointment->cl_dob = $request->cl_dob;
        $appointment->cl_doc_id_number = $request->cl_doc_id_number;
        $appointment->cl_doc_id_state = $request->cl_doc_id_state;
        $appointment->cl_email = $request->cl_email;
        $appointment->cl_mobile_number = $request->cl_mobile_number;
        $appointment->property_address_one = $request->property_address_one;
        $appointment->property_address_two = $request->property_address_two;
        $appointment->property_city = $request->property_city;
        $appointment->property_state = $request->property_state;
        $appointment->property_zip_code = $request->property_zip_code;
        if ($request->has('upload_doc')) {
            $image = $request->file('upload_doc');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/appointmentImage');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = 'default.png';
        }
        $appointment->image = $profile_image;
        $appointment->save();
        if ($appointmentSchedule->background_check == "1") {

            if (!is_null($request->final_firstname)) {
                $checkRecordBg = BackgroundCheck::where('ssn', $request->final_ssn)->first();
                if (!is_null($checkRecordBg)) {
                    $backgroundCheck = $checkRecordBg;
                } else {
                    $backgroundCheck = new BackgroundCheck();
                }
                $backgroundCheck->appointment_schedule_id = $appointmentSchedule->id;
                $backgroundCheck->first_name = $request->final_firstname;
                $backgroundCheck->last_name = $request->final_lastname;
                $backgroundCheck->ssn = $request->final_ssn;
                $backgroundCheck->dob = $request->final_dob;
                $backgroundCheck->city = $request->final_city;
                $backgroundCheck->state = $request->final_state;
                $backgroundCheck->save();
            }
        }


        return redirect()->route('index')->with(['flash_status' => "success", 'flash_message' => "Appointment Updated Successfully!"]);

    }
}

resources/views/realtor/includes/footer.blade.php
<footer class="m-grid__item		m-footer ">
    <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
					<span class="m-footer__copyright">
					 <p>© Copyright SAFECHEX {{ date('Y') }}</p>
					</span>
            </div>
        </div>
    </div>
</footer>

resources/views/realtor/includes/sidebar.blade.php
<button class="m-aside-left-close  m-aside-left-close--skin-dark " id="m_aside_left_close_btn"><i
        class="la la-close"></i></button>
<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">

    <!-- BEGIN: Aside Menu -->
    <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark"
         m-menu-vertical="1" m-menu-scrollable="1" m-menu-dropdown-timeout="500" style="position: relative;">
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">

            <li class="m-menu__item "
                aria-haspopup="true"><a href="{{ route('index') }}" class="m-menu__link "><i
                        class="m-menu__link-icon flaticon-home"></i><span
                        class="m-menu__link-title"> <span
                            class="m-menu__link-wrap"> <span class="m-menu__link-text">Home</span>
											</span></span></a></li>
            <li class="m-menu__item {{ (request()->is('realtor/dashboard')) ? 'activeMenu' : '' }} "
                aria-haspopup="true"><a href="{{ route('realtor.dashboard.index') }}" class="m-menu__link "><i
                        class="m-menu__link-icon flaticon-dashboard"></i><span
                        class="m-menu__link-title"> <span
                            class="m-menu__link-wrap"> <span class="m-menu__link-text">Dashboard</span>
											</span></span></a></li>

            <li class="m-menu__item  {{ (request()->is('realtor/profile') || request()->is('realtor/edit') || request()->is('realtor/edit/*') || request()->is('realtor/update/profile/*') || request()->is('realtor/update') || request()->is('realtor/update/*')) ? 'activeMenu' : '' }} "
                aria-haspopup="true"><a href="{{ route('realtor.profile.index') }}" class="m-menu__link "><i
                        class="m-menu__link-icon flaticon-profile-1"></i><span
                        class="m-menu__link-title"> <span
                            class="m-menu__link-wrap"> <span class="m-menu__link-text">Profile</span>
											</span></span></a></li>


            <li class="m-menu__item {{ (request()->is('realtor/subscribe-history')) ? 'activeMenu' : '' }} "
                aria-haspopup="true"><a href="{{ route('realtor.subscribe.history.index') }}" class="m-menu__link "><i
                        class="m-menu__link-icon flaticon-price-tag"></i><span
                        class="m-menu__link-title"> <span
                            class="m-menu__link-wrap"> <span class="m-menu__link-text">Subscription</span>
											</span></span></a></li>


            <li class="m-menu__item {{ (request()->is('realtor/appointments')) ? 'activeMenu' : '' }} "
                aria-haspopup="true"><a href="{{ route('realtor.appointments.index') }}" class="m-menu__link "><i
                        class="m-menu__link-icon flaticon-price-tag"></i><span
                        class="m-menu__link-title"> <span
                            class="m-menu__link-wrap"> <span class="m-menu__link-text">Appointments</span>
											</span></span></a></li>

            <li class="m-menu__item {{ (request()->is('realtor/notifications')) ? 'activeMenu' : '' }} "
                aria-haspopup="true"><a href="{{ route('realtor.notifications.index') }}" class="m-menu__link "><i
                        class="m-menu__link-icon flaticon-price-tag"></i><span
                        class="m-menu__link-title"> <span
                            class="m-menu__link-wrap"> <span class="m-menu__link-text">Notifications</span>
											</span></span></a></li>


        </ul>
    </div>

    <!-- END: Aside Menu -->
</div>